package App::CatBlog::Model::CatBlogDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'App::CatBlog::Schema::CatBlogDB',

    connect_info => {
        dsn => 'dbi:Pg:dbname=catblog_dev',
        user => 'mak',
        password => '',
    }
);

=head1 NAME

App::CatBlog::Model::CatBlogDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<App::CatBlog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<App::CatBlog::Schema::CatBlogDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.54

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
